FROM node:26-alpine
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
# 🔐 Env DUMMY so Next.js doesnt fail on build
ENV MONGODB_URI="mongodb://placeholder" \
    MONGODB_DATABASE="placeholder"
RUN npm run build
EXPOSE 8080
CMD ["npm", "start"]